language: generic
os: osx
osx_image: xcode8.1
before_install:
- export XCODEBUILD_PATH=$(which xcodebuild)
- export PATH=$PATH:$XCODEBUILD_PATH
- export PATH=$PATH:~/bin
- mkdir ~/go
- export GOPATH=~/go
install:
- xcrun simctl list
- git submodule init
- git submodule update
- gem install xcpretty --user-install -n~/bin
- go get github.com/jwfriese/iossimulator
script:
- go build script/test.go
- ./test 'iOS 10.0' 'iPhone 6'
